version: '3'
services:
  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001
    networks:
      - todoapp
  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
    networks:
      - todoapp
  todotests:
    image: todotests
    restart: always
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
    networks:
      - todoapp

networks:
  todoapp:
